# NoteBook 1: Introduction to programming with Julia

### Contents
1. The basics
2. Julia specific features
3. Loading and installing modules
4. Some cool Julia features

# Part 1: The basics

## Scalars

In [1]:
a = 1

1

In [2]:
typeof(a)

Int64

In [3]:
b = 3.52

3.52

In [4]:
b = 3.52; # silence ouput with semicolon

In [5]:
typeof(b) # returns the type of the b

Float64

In [6]:
sizeof(b) # returns the number of bytes of a variable. 8 bytes = 64 bits

8

In [7]:
# scalar opperations
@show a + b # addition
@show a - b # subtraction
@show a * b # multiplication
@show a / b # divition
@show a ^ b # exponential
@show exp(b) # e ^ a
@show sqrt(b) # √
@show b % a # remainder
@show log(b) # log base e
@show log(10,b) # log base 10
@show log(2,b) # log base 2
@show abs(-2); # absolute value

a + b = 4.52
a - b = -2.52
a * b = 3.52
a / b = 0.2840909090909091
a ^ b = 1.0
exp(b) = 33.78442846384956
sqrt(b) = 1.876166303929372
b % a = 0.52
log(b) = 1.2584609896100056
log(10, b) = 0.546542663478131
log(2, b) = 1.8155754288625725
abs(-2) = 2


## special numbers

In [8]:
pi # pi

π = 3.1415926535897...

In [9]:
im # imaginary unit

im

In [10]:
ℯ # e typed by \euler tab or exp(1)

ℯ = 2.7182818284590...

In [11]:
NaN # not a number

NaN

In [12]:
Inf # Infinity

Inf

In [13]:
# boolean opperations
@show a > b # greater than, returns true or false
@show a < b # less than
@show a <= b # less than or equal to
@show a >= b # greater than or equal to
@show a == b # equality
@show a == 1
@show a != 0 # does not equal

a > b = false
a < b = true
a <= b = true
a >= b = false
a == b = false
a == 1 = true
a != 0 = true


true

In [14]:
# Chaining comparisons
1 < 2 <= 2 < 3 == 3 > 2 >= 1 == 1 < 3 != 5

true

In [15]:
# boolean opperations
@show true && false # and
@show true || false # or
@show true ⊻ true; # xor

true && false = false
true || false = true
true ⊻ true = false


## Strings

In [17]:
# Strings
a = "Hello world!"
println(a) # with new line
@show typeof(a);

Hello world
typeof(a) = String


In [18]:
# printing
name = "Eric"
lastname = "Rouviere"
age = 26
println("My name is ",name,". I am ",age, " years old.")

My name is Eric. I am 26 years old.


In [19]:
# String concatination
name*lastname

"EricRouviere"

In [20]:
# String concatination
name^3

"EricEricEric"

## Arrays

In [21]:
v = [1,2,3]

3-element Vector{Int64}:
 1
 2
 3

In [22]:
v = [1.0,2.0,3.0]

3-element Vector{Float64}:
 1.0
 2.0
 3.0

In [23]:
A = [1 0 2; 0 1 -2; 0 0 1]

3×3 Matrix{Int64}:
 1  0   2
 0  1  -2
 0  0   1

In [24]:
u = ["asdf", 4, 1.2]

3-element Vector{Any}:
  "asdf"
 4
 1.2

## Array indexing (starts at 1, not 0)

In [25]:
@show v[1] # index vector at position 1 
@show A[1,3] # index matrix at position 1,3
@show v[end];

v[1] = 1.0
A[1, 3] = 2
v[end] = 3.0


In [26]:
v[0] # indexing starts at 1

LoadError: BoundsError: attempt to access 3-element Vector{Float64} at index [0]

In [27]:
v[2:3] # index vector at position 2 through 3

2-element Vector{Float64}:
 2.0
 3.0

In [28]:
v[2:end] # index slice of vector 

2-element Vector{Float64}:
 2.0
 3.0

In [29]:
v[:] # index all elements

3-element Vector{Float64}:
 1.0
 2.0
 3.0

In [30]:
A[1:3,2:3] # get slices of matrix

3×2 Matrix{Int64}:
 0   2
 1  -2
 0   1

In [31]:
# edit array
@show v
v[2] = 4
@show v

v = [1.0, 2.0, 3.0]
v = [1.0, 4.0, 3.0]


3-element Vector{Float64}:
 1.0
 4.0
 3.0

## Constructing arrays

In [32]:
# useful array functions
zeros(5) # intialize matrix and fill with zeros

5-element Vector{Float64}:
 0.0
 0.0
 0.0
 0.0
 0.0

In [33]:
zeros(5,3)

5×3 Matrix{Float64}:
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

In [34]:
ones(2,5) # intialize array and fill with 1

2×5 Matrix{Float64}:
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0

In [38]:
rand(2,5,2) # intialize array and fill with uniform randoms

2×5×2 Array{Float64, 3}:
[:, :, 1] =
 0.488029  0.108897  0.355223  0.517079  0.560819
 0.426079  0.150529  0.31334   0.743266  0.829294

[:, :, 2] =
 0.887148  0.423104  0.024774  0.351743  0.990017
 0.263116  0.611467  0.576007  0.066535  0.804654

In [39]:
v = randn(5) # intialize array and fill with unit normals

5-element Vector{Float64}:
  1.626393586970104
 -1.4262588776882767
  0.2996738266772404
  0.2909648382725297
  0.422731722762098

In [42]:
# rand with out argument return 1 random Float
rand()

0.5141845885824694

In [43]:
1:10 # range opporator

1:10

In [44]:
collect(1:10) # convert to array

10-element Vector{Int64}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10

In [45]:
v = LinRange(1,10, 5) # similar to linspace in matlab

5-element LinRange{Float64, Int64}:
 1.0,3.25,5.5,7.75,10.0

In [46]:
# length
length(v)

5

In [47]:
# length of array, ie number of elements
A = rand(100,50)
length(A)

5000

In [48]:
# size of array
size(A)

(100, 50)

## Element wise operations on arrays

Add a dot (.) to the operation. Arrays must be the same size.

In [49]:
v = ones(3)
u = rand(3)

3-element Vector{Float64}:
 0.8063502344178434
 0.3369184909071854
 0.440638724411585

In [50]:
v .+ u

3-element Vector{Float64}:
 1.8063502344178435
 1.3369184909071854
 1.440638724411585

In [52]:
@show v .- u 
@show v .* u
@show v ./ u
@show v .^ u
@show v .% u;

v .- u = [0.19364976558215663, 0.6630815090928146, 0.559361275588415]
v .* u = [0.8063502344178434, 0.3369184909071854, 0.440638724411585]
v ./ u = [1.2401558991571013, 2.968076929548758, 2.269432858710655]
v .^ u = [1.0, 1.0, 1.0]
v .% u = [0.19364976558215663, 0.3261630181856292, 0.11872255117682995]


#### Add dots any scalar function to act element wise.

In [53]:
@show exp.(u) # e ^ 
@show sqrt.(u) # √
@show log.(u) # log base e
@show log.(10,u) # log base 10
@show log.(2,u) # log base 2
@show abs.(u); # absolute value

exp.(u) = [2.2397186032305165, 1.4006248954211211, 1.553699287311396]
sqrt.(u) = [0.8979700632080355, 0.5804468028227784, 0.663806240111966]
log.(u) = [-0.21523709684089878, -1.0879142446285106, -0.81952995829992]
log.(10, u) = [-0.09347628345887816, -0.47247515322610656, -0.35591733864405734]
log.(2, u) = [-0.31052149222770226, -1.569528485638015, -1.1823318066992337]
abs.(u) = [0.8063502344178434, 0.3369184909071854, 0.440638724411585]


## Non-element wise opporations on arrays

In [54]:
u = [1,2,3]
v = [-1,4,5]
@show sum(u); # all parts

sum(u) = 6


In [55]:
@show minimum(u) # minimum
@show maximum(u); # maximum

minimum(u) = 1
maximum(u) = 3


In [56]:
using LinearAlgebra
@show norm(u) # L2 norm
@show norm(u,1) # L1 norm
@show norm(u,Inf); # Infinity norm

norm(u) = 3.7416573867739413
norm(u, 1) = 6.0
norm(u, Inf) = 3.0


In [57]:
# dot product
@show dot(u,v)
@show u ⋅ v; # dot product, \cdot

dot(u, v) = 22
u ⋅ v = 22


In [58]:
2 * v # scalar vector product

3-element Vector{Int64}:
 -2
  8
 10

In [59]:
v + u # vector addition

3-element Vector{Int64}:
 0
 6
 8

In [60]:
A = rand(3,3)
A * v # matrix vector product

3-element Vector{Float64}:
 5.042018553477709
 4.639857144499304
 3.710860433737832

In [62]:
B = rand(5,3)
B * A # Matrix Matrix product

5×3 Matrix{Float64}:
 0.8003    1.13689  0.765336
 0.864392  1.17748  0.829669
 0.635814  1.29797  0.59958
 0.451506  1.19936  0.345149
 1.06342   1.19137  1.07997

In [63]:
# Transpose (or adjoint)
v'

1×3 adjoint(::Vector{Int64}) with eltype Int64:
 -1  4  5

In [64]:
B'

3×5 adjoint(::Matrix{Float64}) with eltype Float64:
 0.392421  0.406787  0.547128  0.0577051  0.704368
 0.78842   0.884875  0.252135  0.469256   0.934132
 0.522035  0.495078  0.976991  0.971053   0.327749

In [65]:
u' * A * u # Quadratic form

17.117271827426478

In [66]:
det(A) #determinant 

0.07109766488746298

In [67]:
inv(A) #inverse of A 

3×3 Matrix{Float64}:
 -6.91521    9.64449  -2.93259
  0.738627  -1.10681   1.45823
  6.64665   -7.41078   1.58249

## Control Flow

#### If else blocks

In [68]:
a = 55
if a < 0
    println("a is less than 0")
elseif a < 10
    println("a is less than 10 but greater than 0")
else
    println("a is greater than 10")
end

a is greater than 10


#### For loops

In [69]:
for i in 1:10
    println(i)
end

1
2
3
4
5
6
7
8
9
10


In [70]:
# you can use matlab syntax with "="
for i = 1:10
    println(i)
end

1
2
3
4
5
6
7
8
9
10


In [71]:
for i in 1:3
    for j in 1:3
        println("i = ",i,", j = ",j)
    end
end

i = 1, j = 1
i = 1, j = 2
i = 1, j = 3
i = 2, j = 1
i = 2, j = 2
i = 2, j = 3
i = 3, j = 1
i = 3, j = 2
i = 3, j = 3


In [72]:
for i in 1:3, j in 1:3
    println("i = ",i,", j = ",j)
end

i = 1, j = 1
i = 1, j = 2
i = 1, j = 3
i = 2, j = 1
i = 2, j = 2
i = 2, j = 3
i = 3, j = 1
i = 3, j = 2
i = 3, j = 3


### while loops

In [73]:
a = 0
while a < 5
    a = a + 1
    println(a)
end

1
2
3
4
5


In [74]:
# It is common to use an "updating opporator"

a = 0
while a < 5
    a += 1 # same as `a=a+1` 
    println(a)
end

1
2
3
4
5


In [ ]:
# many updating opporator exist
# +=  -=  *=  /=  \=  ÷=  %=  ^=  &=  |=  ⊻= >>=  <<=

## Functions

#### Two ways to define functions. For simple function write them a you would in math

In [75]:
f(x,y) = -2*x^2 + 3*y + 14

f (generic function with 1 method)

In [76]:
f(5,1)

-33

#### For longer functions its useful to use multi line definitions

In [77]:
function f(x,y)
    z = -2*x^2 + 3*y + 14
    return z
end

f (generic function with 1 method)

In [78]:
f(5,1)

-33

In [80]:
# When you dont want the function to return a value, return nothing.
function printHelloWorld()
    println("Hello world")
    return nothing
end

printHelloWorld (generic function with 1 method)

In [85]:
printHelloWorld()

Hello world


#### Keyword arguments

In [86]:
function g(x,y; a=1,b=2,c=3)
    return a*x + b*y + c
end

g (generic function with 1 method)

In [87]:
g(1,3)

10

In [88]:
g(1,3, a=10,b=-10,c=0)

-20

## Loading modules (packages)

In [89]:
using LinearAlgebra, Random

To install other packages use `]`

In [90]:
] add LaTeXStrings

    Updating registry at `~/.julia/registries/General`
    Updating git-repo `https://github.com/JuliaRegistries/General.git`
   Resolving package versions...
  No Changes to `~/.julia/environments/v1.7/Project.toml`
  No Changes to `~/.julia/environments/v1.7/Manifest.toml`


Suppose I write my own module called ExampleModule.jl and its save in `src/`.

In [91]:
pwd() # print working directory

"/home/erouviere/Dropbox/protevo/projects/BPHYS_workshop_2022/notebooks"

In [93]:
readdir("../src/") # lists the files in the working directory

7-element Vector{String}:
 "Elastic_N3.jl"
 "Elastic_N4.jl"
 "Elastic_N5.jl"
 "Elastic_N6.jl"
 "Elastic_N7.jl"
 "ExampleModule.jl"
 "LinearElastic.jl"

In [94]:
push!(LOAD_PATH, "../src/") # add working director to LOAD_PATH

4-element Vector{String}:
 "@"
 "@v#.#"
 "@stdlib"
 "../src/"

In [95]:
using ExampleModule

┌ Info: Precompiling ExampleModule [top-level]
└ @ Base loading.jl:1423


In [96]:
# call the exported function
exampleFunction()

This is a fuction from my module ExampleModule.jl


# Part 2: Important Julia design features to keep in mind 

## Scope
Not all of the code knows about all variables. 

Variables defined within a function **are not** known to code outside of the function

In [ ]:
function f()
    a = 1
    return nothing
end

a=2
f()
a

Variables defined outside a function **are** known within the function

In [ ]:
function f()
    println(a)
    return nothing
end

a = 2
f()

If a variable **is** defined before a loop, the changes to the variable will be seen outside the loop

In [ ]:
a = 1
for i in 1:2
    a = 1
end
a

If a variable **is not** defined before a loop, the variable is not known outside the loop

In [ ]:
a = 1
for i in 1:2
    p = 3
end
p

## Arrays are not copied by default
similar to numpy, not like matlab.

In [ ]:
v = [1,2,3]

In [ ]:
u = v

In [ ]:
u[1] = 0
u

In [ ]:
v # v is edited too.

In [ ]:
u === v # u and v reference same object in memory

use copy to create a **new** array with the same entries

In [ ]:
v = [1,2,3]
u = copy(v)
u[1] = 0
u

In [ ]:
v

In [ ]:
v === u 

## Julia is "pass by reference" not "pass by value"

In [ ]:
function f(v)
    v[1] = 0
    return nothing
end

v = [1,2,3]
f(v)
v

Functions that edit their arguments are called inplace functions (often symbolized with ! to help the reader).

In [ ]:
v = [1,2,3]
fill!(v, 0)
v

# Part 3: Loading and installing modules and packages.

### Loading packages

To load julia modules use the `using` command

In [ ]:
using LinearAlgebra 
using Random

Suppose I write my own module called `ExampleModule.jl` and its save in current working directory. Use `pwd()` to get the working directory.

In [ ]:
pwd() # print working directory

Add the directory contain my module to the `LOAD_PATH`.

In [ ]:
push!(LOAD_PATH, pwd()) # add working director to LOAD_PATH

In [ ]:
using ExampleModule

In [ ]:
# call the exported function
exampleFunction()

### Installing packages
packages are installed using the Julia package manger `Pkg`.

In [ ]:
# load the package manager
using Pkg

In [ ]:
Pkg.add("PyPlot") # A julia wrapper around matplotlib pyplot

In [ ]:
using PyPlot # 

In [ ]:
plot(1:10, rand(10));

# Part 4: Some cool Julia features

### Any unicode character is fair game

for example type `\lambda` then press tab.

In [ ]:
λ = 5
β = 3

Unicode works for functions too

In [ ]:
Σ(v) = sum(v)
v = rand(10)
Σ(v)

Emojies are unicode `\:hourglass_flowing_sand:`

In [ ]:
function ⏳(seconds)
    sleep(seconds)
    println("time to get up!")
end

In [ ]:
⏳(2)

To see the unicode full list go to (https://docs.julialang.org/en/v1/manual/unicode-input/)

## Documentation is build in
prefix the item you when to find with `?`

In [ ]:
?print

In [ ]:
?for

In [ ]:
; ls

## Bash shell is built in
type `;` then your shell command

In [ ]:
; pwd

In [ ]:
; ls

In [ ]:
; echo 5

In [ ]:
; df -H

## Package manager is build in
type `]` then a package manager command

In [ ]:
] add BenchMarkTools