# NoteBook 1: Introduction to programming with Julia

### Contents
1. The basics
2. Julia specific features
3. Loading and installing modules
4. Some cool Julia features

# Part 1: The basics

## Scalars

In [1]:
a = 1

1

In [2]:
typeof(a)

Int64

In [3]:
b = 3.52

3.52

In [4]:
b = 3.52; # silence ouput with semicolon

In [5]:
typeof(b) # returns the type of the b

Float64

In [6]:
sizeof(b) # returns the number of bytes of a variable. 8 bytes = 64 bits

8

In [7]:
# scalar opperations
@show a + b # addition
@show a - b # subtraction
@show a * b # multiplication
@show a / b # divition
@show a ^ b # exponential
@show exp(b) # e ^ a
@show sqrt(b) # √
@show b % a # remainder
@show log(b) # log base e
@show log(10,b) # log base 10
@show log(2,b) # log base 2
@show abs(-2); # absolute value

a + b = 4.52
a - b = -2.52
a * b = 3.52
a / b = 0.2840909090909091
a ^ b = 1.0
exp(b) = 33.78442846384956
sqrt(b) = 1.876166303929372
b % a = 0.52
log(b) = 1.2584609896100056
log(10, b) = 0.546542663478131
log(2, b) = 1.8155754288625725
abs(-2) = 2


## special numbers

In [8]:
pi # pi

π = 3.1415926535897...

In [9]:
im # imaginary unit

im

In [10]:
ℯ # e typed by \euler tab or exp(1)

ℯ = 2.7182818284590...

In [11]:
NaN # not a number

NaN

In [12]:
Inf # Infinity

Inf

In [13]:
# boolean opperations
@show a > b # greater than, returns true or false
@show a < b # less than
@show a <= b # less than or equal to
@show a >= b # greater than or equal to
@show a == b # equality
@show a == 1
@show a != 0 # does not equal

a > b = false
a < b = true
a <= b = true
a >= b = false
a == b = false
a == 1 = true
a != 0 = true


true

In [14]:
# Chaining comparisons
1 < 2 <= 2 < 3 == 3 > 2 >= 1 == 1 < 3 != 5

true

In [15]:
# boolean opperations
@show true && false # and
@show true || false # or
@show true ⊻ true; # xor

true && false = false
true || false = true
true ⊻ true = false


## Strings

In [16]:
# Strings
a = "Hello world!"
println(a) # with new line
@show typeof(a);

Hello world!
typeof(a) = String


In [17]:
# printing
name = "Eric"
lastname = "Rouviere"
age = 26
println("My name is ",name,". I am ",age, " years old.")

My name is Eric. I am 26 years old.


In [18]:
# String concatination
name*lastname

"EricRouviere"

In [19]:
# String concatination
name^3

"EricEricEric"

## Arrays

In [22]:
v = [1,2,3]

3-element Vector{Int64}:
 1
 2
 3

In [23]:
v = [1.0,2.0,3.0]

3-element Vector{Float64}:
 1.0
 2.0
 3.0

In [24]:
A = [1 0 2; 0 1 -2; 0 0 1]

3×3 Matrix{Int64}:
 1  0   2
 0  1  -2
 0  0   1

In [25]:
u = ["asdf", 4, 1.2]

3-element Vector{Any}:
  "asdf"
 4
 1.2

## Array indexing (starts at 1, not 0)

In [26]:
@show v[1] # index vector at position 1 
@show A[1,3] # index matrix at position 1,3
@show v[end];

v[1] = 1.0
A[1, 3] = 2
v[end] = 3.0


In [27]:
v[0] # indexing starts at 1

LoadError: BoundsError: attempt to access 3-element Vector{Float64} at index [0]

In [28]:
v[2:3] # index vector at position 2 through 3

2-element Vector{Float64}:
 2.0
 3.0

In [29]:
v[2:end] # index slice of vector 

2-element Vector{Float64}:
 2.0
 3.0

In [30]:
v[:] # index all elements

3-element Vector{Float64}:
 1.0
 2.0
 3.0

In [31]:
A[1:3,2:3] # get slices of matrix

3×2 Matrix{Int64}:
 0   2
 1  -2
 0   1

In [32]:
# edit array
@show v
v[2] = 4
@show v

v = [1.0, 2.0, 3.0]
v = [1.0, 4.0, 3.0]


3-element Vector{Float64}:
 1.0
 4.0
 3.0

## Constructing arrays

In [33]:
# useful array functions
zeros(5) # intialize matrix and fill with zeros

5-element Vector{Float64}:
 0.0
 0.0
 0.0
 0.0
 0.0

In [34]:
zeros(5,3)

5×3 Matrix{Float64}:
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

In [35]:
ones(2,5) # intialize array and fill with 1

2×5 Matrix{Float64}:
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0

In [36]:
rand(2,5,2) # intialize array and fill with uniform randoms

2×5×2 Array{Float64, 3}:
[:, :, 1] =
 0.731378  0.0747399  0.837704  0.94854   0.0169449
 0.475959  0.409535   0.570768  0.197842  0.0796715

[:, :, 2] =
 0.706695  0.217768  0.153424  0.784718  0.0123164
 0.38194   0.174398  0.306516  0.525474  0.915232

In [37]:
v = randn(5) # intialize array and fill with unit normals

5-element Vector{Float64}:
 0.4109469754381336
 1.0963626005365963
 0.5780712071581579
 0.6416745341171629
 0.49030998541603593

In [38]:
# rand with out argument return 1 random Float
rand()

0.5168921024681457

In [39]:
1:10 # range opporator

1:10

In [40]:
collect(1:10) # convert to array

10-element Vector{Int64}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10

In [41]:
v = LinRange(1,10, 5) # similar to linspace in matlab

5-element LinRange{Float64, Int64}:
 1.0,3.25,5.5,7.75,10.0

In [42]:
# length
length(v)

5

In [43]:
# length of array, ie number of elements
A = rand(100,50)
length(A)

5000

In [44]:
# size of array
size(A)

(100, 50)

## Element wise operations on arrays

Add a dot (.) to the operation. Arrays must be the same size.

In [45]:
v = ones(3)
u = rand(3)

3-element Vector{Float64}:
 0.7762303561539177
 0.6507342089778055
 0.2934757627163215

In [46]:
v .+ u

3-element Vector{Float64}:
 1.7762303561539177
 1.6507342089778057
 1.2934757627163216

In [47]:
@show v .- u 
@show v .* u
@show v ./ u
@show v .^ u
@show v .% u;

v .- u = [0.22376964384608233, 0.34926579102219446, 0.7065242372836785]
v .* u = [0.7762303561539177, 0.6507342089778055, 0.2934757627163215]
v ./ u = [1.2882773677582269, 1.5367257264234386, 3.407436412275778]
v .^ u = [1.0, 1.0, 1.0]
v .% u = [0.22376964384608233, 0.34926579102219446, 0.11957271185103557]


#### Add dots any scalar function to act element wise.

In [48]:
@show exp.(u) # e ^ 
@show sqrt.(u) # √
@show log.(u) # log base e
@show log.(10,u) # log base 10
@show log.(2,u) # log base 2
@show abs.(u); # absolute value

exp.(u) = [2.173264372134179, 1.9169477527127148, 1.3410806748635138]
sqrt.(u) = [0.8810393612965982, 0.8066809833991412, 0.5417340331900161]
log.(u) = [-0.25330595213656243, -0.429654001283089, -1.225960223306808]
log.(10, u) = [-0.11000937724615828, -0.18659636188489823, -0.5324277600150251]
log.(2, u) = [-0.36544324097507574, -0.6198596969492128, -1.7686867344918582]
abs.(u) = [0.7762303561539177, 0.6507342089778055, 0.2934757627163215]


## Non-element wise opporations on arrays

In [49]:
u = [1,2,3]
v = [-1,4,5]
@show sum(u); # all parts

sum(u) = 6


In [50]:
@show minimum(u) # minimum
@show maximum(u); # maximum

minimum(u) = 1
maximum(u) = 3


In [51]:
using LinearAlgebra
@show norm(u) # L2 norm
@show norm(u,1) # L1 norm
@show norm(u,Inf); # Infinity norm

norm(u) = 3.7416573867739413
norm(u, 1) = 6.0
norm(u, Inf) = 3.0


In [52]:
# dot product
@show dot(u,v)
@show u ⋅ v; # dot product, \cdot

dot(u, v) = 22
u ⋅ v = 22


In [53]:
2 * v # scalar vector product

3-element Vector{Int64}:
 -2
  8
 10

In [54]:
v + u # vector addition

3-element Vector{Int64}:
 0
 6
 8

In [55]:
A = rand(3,3)
A * v # matrix vector product

3-element Vector{Float64}:
 3.6643323887400907
 5.014889104135602
 1.7588382463912637

In [56]:
B = rand(5,3)
B * A # Matrix Matrix product

5×3 Matrix{Float64}:
 0.99734   0.628819  0.692248
 1.24511   0.936205  0.977884
 1.60795   1.21381   1.20426
 0.927324  0.65658   0.64346
 0.223704  0.215399  0.196713

In [57]:
# Transpose (or adjoint)
v'

1×3 adjoint(::Vector{Int64}) with eltype Int64:
 -1  4  5

In [58]:
B'

3×5 adjoint(::Matrix{Float64}) with eltype Float64:
 0.92905   0.804504  0.975137  0.648944  0.02138
 0.257148  0.76852   0.803965  0.275145  0.230643
 0.162187  0.333814  0.94583   0.65869   0.219726

In [59]:
u' * A * u # Quadratic form

15.139364662397993

In [60]:
det(A) #determinant 

-0.031531633491720557

In [62]:
inv(A) #inverse of A 

3×3 Matrix{Float64}:
  2.22763   -2.32559    1.42128
 -2.98614    0.509973   7.04144
  0.845195   3.25877   -8.20964

## Control Flow

#### If else blocks

In [63]:
a = 55
if a < 0
    println("a is less than 0")
elseif a < 10
    println("a is less than 10 but greater than 0")
else
    println("a is greater than 10")
end

a is greater than 10


#### For loops

In [64]:
for i in 1:10
    println(i)
end

1
2
3
4
5
6
7
8
9
10


In [65]:
# you can use matlab syntax with "="
for i = 1:10
    println(i)
end

1
2
3
4
5
6
7
8
9
10


In [67]:
for i in 1:3
    for j in 1:3
        println("i = ",i,", j = ",j)
    end
end

i = 1, j = 1
i = 1, j = 2
i = 1, j = 3
i = 2, j = 1
i = 2, j = 2
i = 2, j = 3
i = 3, j = 1
i = 3, j = 2
i = 3, j = 3


In [68]:
for i in 1:3, j in 1:3
    println("i = ",i,", j = ",j)
end

i = 1, j = 1
i = 1, j = 2
i = 1, j = 3
i = 2, j = 1
i = 2, j = 2
i = 2, j = 3
i = 3, j = 1
i = 3, j = 2
i = 3, j = 3


### while loops

In [69]:
a = 0
while a < 5
    a = a + 1
    println(a)
end

1
2
3
4
5


In [70]:
# It is common to use an "updating opporator"

a = 0
while a < 5
    a += 1 # same as `a=a+1` 
    println(a)
end

1
2
3
4
5


In [ ]:
# many updating opporator exist
# +=  -=  *=  /=  \=  ÷=  %=  ^=  &=  |=  ⊻= >>=  <<=

## Functions

#### Two ways to define functions. For simple function write them a you would in math

In [71]:
f(x,y) = -2*x^2 + 3*y + 14

f (generic function with 1 method)

In [72]:
f(5,1)

-33

#### For longer functions its useful to use multi line definitions

In [80]:
function f(x,y)
    z = -2*x^2 + 3*y + 14
    return z
end

f (generic function with 1 method)

In [81]:
f(5,1)

-33

In [82]:
# When you dont want the function to return a value, return nothing.
function printHelloWorld()
    println("Hello world")
    return nothing
end

printHelloWorld (generic function with 1 method)

In [83]:
printHelloWorld()

Hello world


#### Keyword arguments

In [84]:
function g(x,y; a=1,b=2,c=3)
    return a*x + b*y + c
end

g (generic function with 1 method)

In [85]:
g(1,3)

10

In [86]:
g(1,3, a=10,b=-10,c=0)

-20

# Part 2: Important Julia design features to keep in mind 

## Scope
Not all of the code knows about all variables. 

Variables defined within a function **are not** known to code outside of the function

In [87]:
function f()
    a = 1
    return nothing
end

a=2
f()
a

2

Variables defined outside a function **are** known within the function

In [92]:

function f(a)
    global a 
    a = 10
    println(a)
    return nothing
end

global a = 2
f(a)
@show a

10
a = 10


10

If a variable **is** defined before a loop, the changes to the variable will be seen outside the loop

In [95]:
a = 1
for i in 1:2
    a = 2
end
a

2

If a variable **is not** defined before a loop, the variable is not known outside the loop

In [96]:
a = 1
for i in 1:2
    p = 3
end
p

LoadError: UndefVarError: p not defined

## Arrays are not copied by default
similar to numpy, not like matlab.

In [97]:
v = [1,2,3]

3-element Vector{Int64}:
 1
 2
 3

In [98]:
u = v

3-element Vector{Int64}:
 1
 2
 3

In [99]:
u[1] = 0
u

3-element Vector{Int64}:
 0
 2
 3

In [100]:
v # v is edited too.

3-element Vector{Int64}:
 0
 2
 3

In [101]:
u === v # u and v reference same object in memory

true

use copy to create a **new** array with the same entries

In [105]:
v = [1,2,3]
u = copy(v)
u[1] = 0
u

3-element Vector{Int64}:
 1
 2
 3

In [106]:
v

3-element Vector{Int64}:
 1
 2
 3

In [107]:
v === u 

false

## Julia is "pass by reference" not "pass by value"

In [108]:
function f(v)
    v[1] = 0
    return nothing
end

v = [1,2,3]
f(v)
v

3-element Vector{Int64}:
 0
 2
 3

Functions that edit their arguments are called inplace functions (often symbolized with ! to help the reader).

In [110]:
v = [1,2,3]
fill!(v, 0)
v

3-element Vector{Int64}:
 0
 0
 0

# Part 3: Loading and installing modules and packages.

### Loading packages

To load julia modules use the `using` command

In [111]:
using LinearAlgebra, Random

## Lets write our own module. 
Make a file in `BPHYS_workshop_2022/src/` called `ExampleModule.jl` and write the following lines in it.

    module ExampleModule
    export exampleFunction
    function exampleFunction()
        println("This is a fuction from my module ExampleModule.jl")
        return nothing
    end
    end 




In [112]:
pwd() # print working directory

"/Users/ericrouviere/Dropbox/protevo/projects/BPHYS_workshop_2022/notebooks"

In [113]:
readdir("../src/") # lists the files in the working directory

8-element Vector{String}:
 ".ipynb_checkpoints"
 "Elastic_N3.jl"
 "Elastic_N4.jl"
 "Elastic_N5.jl"
 "Elastic_N6.jl"
 "Elastic_N7.jl"
 "ExampleModule.jl"
 "LinearElastic.jl"

In [114]:
LOAD_PATH

3-element Vector{String}:
 "@"
 "@v#.#"
 "@stdlib"

In [115]:
push!(LOAD_PATH, "../src/") # add working director to LOAD_PATH

4-element Vector{String}:
 "@"
 "@v#.#"
 "@stdlib"
 "../src/"

In [116]:
using ExampleModule

┌ Info: Precompiling ExampleModule [top-level]
└ @ Base loading.jl:1664


In [117]:
# call the exported function
exampleFunction()

This is a fuction from my module ExampleModule.jl


### Installing packages
packages are installed using the Julia package manger `Pkg`.

In [ ]:
# load the package manager
using Pkg

In [ ]:
Pkg.add("PyPlot") # A julia wrapper around matplotlib pyplot

In [ ]:
using PyPlot # 

In [ ]:
plot(1:10, rand(10));

# Part 4: Some cool Julia features

### Any unicode character is fair game

for example type `\lambda` then press tab.

In [120]:
λ = 5
β = 3

3

Unicode works for functions too

In [ ]:
Σ(v) = sum(v)
v = rand(10)
Σ(v)

Emojies are unicode `\:hourglass_flowing_sand:`

In [122]:
function ⏳(seconds)
    sleep(seconds)
    println("time to get up!")
end

⏳ (generic function with 1 method)

In [123]:
⏳(2)

time to get up!


To see the unicode full list go to (https://docs.julialang.org/en/v1/manual/unicode-input/)

## Documentation (?), Shell (;) and Package Manager (]) is built in but can only be used in the julia terminal.

Try typing the fooling a julia terminal.

`? sum` 

`; ls`

`] add LaTeXStrings`